"""add something

Revision ID: 7dd2179f3253
Revises: 9c52058f7d37
Create Date: 2026-05-01 16:24:07.680565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dd2179f3253'
down_revision: Union[str, Sequence[str], None] = '9c52058f7d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_settings', sa.Column('bot_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_bot_settings_key'), table_name='bot_settings')
    op.drop_index(op.f('ix_bot_settings_user_id'), table_name='bot_settings')
    op.create_foreign_key(None, 'bot_settings', 'bots', ['bot_id'], ['id'])
    op.drop_column('bot_settings', 'user_id')
    op.create_foreign_key(None, 'bots', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'bots', 'users', ['owner_id'], ['id'])
    op.add_column('conversations', sa.Column('bot_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_conversations_external_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.create_foreign_key(None, 'conversations', 'bots', ['bot_id'], ['id'])
    op.drop_column('conversations', 'external_id')
    op.drop_column('conversations', 'user_id')
    op.add_column('leads', sa.Column('bot_id', sa.Integer(), nullable=True))
    op.alter_column('leads', 'whatsapp',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_leads_owner_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_telegram_id'), table_name='leads')
    op.create_index(op.f('ix_leads_telegram_id'), 'leads', ['telegram_id'], unique=False)
    op.drop_index(op.f('ix_leads_whatsapp'), table_name='leads')
    op.create_index(op.f('ix_leads_whatsapp'), 'leads', ['whatsapp'], unique=False)
    op.create_index(op.f('ix_leads_bot_id'), 'leads', ['bot_id'], unique=False)
    op.drop_constraint(op.f('leads_owner_id_fkey'), 'leads', type_='foreignkey')
    op.drop_constraint(op.f('leads_assigned_to_fkey'), 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'bots', ['bot_id'], ['id'])
    op.drop_column('leads', 'chat_history')
    op.drop_column('leads', 'owner_id')
    op.drop_column('leads', 'assigned_to')
    op.drop_column('leads', 'response_count')
    op.drop_column('leads', 'last_followup')
    op.drop_column('leads', 'converted')
    op.drop_column('leads', 'next_followup')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_constraint(op.f('users_telegram_id_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'bot_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bot_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('telegram_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_telegram_id_key'), 'users', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('leads', sa.Column('next_followup', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('converted', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('last_followup', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('response_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('leads', sa.Column('chat_history', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key(op.f('leads_assigned_to_fkey'), 'leads', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(op.f('leads_owner_id_fkey'), 'leads', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_leads_bot_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_whatsapp'), table_name='leads')
    op.create_index(op.f('ix_leads_whatsapp'), 'leads', ['whatsapp'], unique=True)
    op.drop_index(op.f('ix_leads_telegram_id'), table_name='leads')
    op.create_index(op.f('ix_leads_telegram_id'), 'leads', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_leads_owner_id'), 'leads', ['owner_id'], unique=False)
    op.alter_column('leads', 'whatsapp',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('leads', 'bot_id')
    op.add_column('conversations', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversations_external_id'), 'conversations', ['external_id'], unique=False)
    op.drop_column('conversations', 'bot_id')
    op.drop_constraint(None, 'bots', type_='foreignkey')
    op.drop_constraint(None, 'bots', type_='foreignkey')
    op.add_column('bot_settings', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bot_settings', type_='foreignkey')
    op.create_index(op.f('ix_bot_settings_user_id'), 'bot_settings', ['user_id'], unique=False)
    op.create_index(op.f('ix_bot_settings_key'), 'bot_settings', ['key'], unique=False)
    op.drop_column('bot_settings', 'bot_id')
    # ### end Alembic commands ###
