"""UPDATE Knowledge

Revision ID: 8cca9b598e0e
Revises: 57c7d19f4c66
Create Date: 2026-05-09 22:26:46.337157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cca9b598e0e'
down_revision: Union[str, Sequence[str], None] = '57c7d19f4c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id', 'question', name='unique_bot_question')
    )
    with op.batch_alter_table('bot_faq', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_faq_bot_id'), ['bot_id'], unique=False)

    op.create_table('bot_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_knowledge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_knowledge_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_knowledge_category'), ['category'], unique=False)

    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_response', sa.Text(), nullable=True))

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minat', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('intent', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_summary', sa.Text(), nullable=True))
        batch_op.alter_column(
            'umur_anak',
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            existing_nullable=True,
            postgresql_using="NULLIF(umur_anak, '')::integer"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.alter_column('umur_anak',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),  
               existing_nullable=True)
        batch_op.drop_column('last_summary')
        batch_op.drop_column('intent')
        batch_op.drop_column('minat')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('raw_response')

    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('bot_knowledge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_knowledge_category'))
        batch_op.drop_index(batch_op.f('ix_bot_knowledge_bot_id'))

    op.drop_table('bot_knowledge')
    with op.batch_alter_table('bot_faq', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_faq_bot_id'))

    op.drop_table('bot_faq')
    # ### end Alembic commands ###
