"""fix conversation index

Revision ID: 9337fba88f9d
Revises: a49dd7d51c22
Create Date: 2026-05-14 22:18:09.556204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9337fba88f9d'
down_revision: Union[str, Sequence[str], None] = 'a49dd7d51c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_faq', schema=None) as batch_op:
        batch_op.create_index('idx_botfaq_bot', ['bot_id'], unique=False)

    with op.batch_alter_table('bot_knowledge', schema=None) as batch_op:
        batch_op.create_index('idx_botknowledge_bot', ['bot_id'], unique=False)

    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_notes', sa.Text(), nullable=True))

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('idx_conversation_lead', ['lead_id', 'created_at'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'bots', ['bot_id'], ['id'])

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('revenue', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_leads_invoice_id'), ['invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_invoice_id'))
        batch_op.drop_column('cost')
        batch_op.drop_column('revenue')
        batch_op.drop_column('invoice_id')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('idx_conversation_lead')

    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.drop_column('payment_notes')

    with op.batch_alter_table('bot_knowledge', schema=None) as batch_op:
        batch_op.drop_index('idx_botknowledge_bot')

    with op.batch_alter_table('bot_faq', schema=None) as batch_op:
        batch_op.drop_index('idx_botfaq_bot')

    # ### end Alembic commands ###
