"""add telegram_id

Revision ID: 9c52058f7d37
Revises: 8877407c484f
Create Date: 2026-04-29 23:59:05.655559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c52058f7d37'
down_revision: Union[str, Sequence[str], None] = '8877407c484f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bot_settings_key_key'), 'bot_settings', type_='unique')
    op.create_index(op.f('ix_bot_settings_key'), 'bot_settings', ['key'], unique=False)
    op.drop_column('bot_settings', 'bot_active')
    op.drop_column('conversations', 'owner_id')
    op.add_column('users', sa.Column('telegram_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'telegram_id')
    op.add_column('conversations', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bot_settings', sa.Column('bot_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_bot_settings_key'), table_name='bot_settings')
    op.create_unique_constraint(op.f('bot_settings_key_key'), 'bot_settings', ['key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
