"""UPGRADE AI

Revision ID: a49dd7d51c22
Revises: 8cca9b598e0e
Create Date: 2026-05-14 17:21:55.469678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a49dd7d51c22'
down_revision: Union[str, Sequence[str], None] = '8cca9b598e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('invoice_code', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_code')
    )
    op.create_table('payment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payment_transfer_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payment_qris_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rekening', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('qris_url', sa.Text(), nullable=True))

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('message_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('message_count')
        batch_op.drop_column('payment_status')

    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.drop_column('qris_url')
        batch_op.drop_column('rekening')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('payment_qris_enabled')
        batch_op.drop_column('payment_transfer_enabled')
        batch_op.drop_column('payment_enabled')

    op.drop_table('payment_logs')
    op.drop_table('invoices')
    # ### end Alembic commands ###
