"""init clean

Revision ID: f89c5569da23
Revises: 
Create Date: 2026-05-04 20:19:05.543106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89c5569da23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_settings_bot_id'), ['bot_id'], unique=False)

    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persona_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('system_prompt', sa.Text(), nullable=True))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_lead_id'), ['lead_id'], unique=False)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_human_takeover', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ai_enabled', sa.Boolean(), nullable=True))
        batch_op.create_index('idx_bot_lastchat', ['bot_id', 'last_chat'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)
        batch_op.create_unique_constraint('unique_bot_telegram', ['bot_id', 'telegram_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint('unique_bot_telegram', type_='unique')
        batch_op.drop_index(batch_op.f('ix_leads_status'))
        batch_op.drop_index('idx_bot_lastchat')
        batch_op.drop_column('ai_enabled')
        batch_op.drop_column('is_human_takeover')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_lead_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_created_at'))
        batch_op.drop_index(batch_op.f('ix_conversations_bot_id'))

    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
        batch_op.drop_column('system_prompt')
        batch_op.drop_column('persona_type')

    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_settings_bot_id'))

    # ### end Alembic commands ###
